#! /bin/sh

source /etc/profile

case "$1" in
  start)
    echo "Initializing the display panel..."
    modprobe panel-jinglitai-jlt4013a
    ;;
  stop)
    echo "Skipping deinitializing the display panel..."
    # modprobe -r panel-jinglitai-jlt4013a
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;

esac

exit 0
